{
  "name": "ChatPro - دردشة فورية",
  "short_name": "ChatPro",
  "description": "تطبيق دردشة فوري متطور مع إشعارات الخلفية",
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "background_color": "#6a11cb",
  "theme_color": "#6a11cb",
  "orientation": "portrait"
}
